# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: GalaxyChop CI

on:
  - push
  - pull_request

env:
  default-python: '3.11'

jobs:
  testing:
    uses: "BrunoCeliz/galaxy-chop/.github/workflows/tests.yml@b5ba226d102e0c24d31bc8f606816925fef6aafc"
  