# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: GalaxyChop CI

on:
  push:
    branches: 
      - "dev"
  pull_request:
      branches: 
      - "dev"

env:
  default-python: '3.11'

jobs:
  testing:
    uses: ./blob/dev/.github/workflows/tests.yml@aa7b8673d28d2c530b4bc1f8d049f715e57d4e98
  