# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: GalaxyChop CI

on:
  - push
  - pull_request

jobs:
  testing:
    uses: vcristiani/galaxy-chop/.github/workflows/tests.yml@HEAD

