# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: GalaxyChop CI

on:
  - push
  - pull_request

env:
  default-python: '3.9'

jobs:
  testing:
    uses: "BrunoCeliz/galaxy-chop/.github/workflows/tests.yml@3c38813a2c2cc9d2d1b78f0538b1deedfeef9b44"
  