# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: GalaxyChop CI

on:
  push:
    branches: 
      - "dev"
  pull_request:
      branches: 
      - "dev"

env:
  default-python: '3.11'

jobs:
  testing:
    uses: BrunoCeliz/galaxy-chop/.github/workflows/tests.yml@7e90df8a676a7996440a412102b5db3336213845
  