# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: GalaxyChop CI

on:
  push:
    branches: 
      - "dev"
  pull_request:
      branches: 
      - "dev"

env:
  default-python: '3.11'

jobs:
  testing:
    uses: vcristiani/galaxy-chop/.github/workflows/tests.yml@6755fca5b3b61910a085a25f94a33e2fb4c1fc3e

