# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: GalaxyChop CI

on:
  push:
    branches: 
      - "dev"
  pull_request:
      branches: 
      - "dev"

env:
  default-python: '3.11'

jobs:
  testing:
    uses: BrunoCeliz/galaxy-chop/blob/dev/.github/workflows/tests.yml@fdeaca7eda1fbbea20f0cc4f24711834b3a1b0e3
  