name:  Galaxy Chop Actions Docs

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        env:
          - TOXENV: docs
    steps:
      - uses: actions/checkout@master
        uses: actions/setup-python@v1
      - uses: docker://pandoc/core:2.9
        with:
          args: "--help" # gets appended to pandoc command
          python-version: ${{ matrix.python-version}}
      - name: Install tox
        run: pip install tox
      - name: Test with tox ${{ matrix.env.TOXENV }}
        env: ${{ matrix.env }}
        run: tox -r
      